fluentd:
  build: ./fluentd
  links:
   - "elasticsearch"
  volumes:
   - ./nginx/log:/fluentd/log

elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
  ports:
    - "9200:9200"
    - "9300:9300"
  environment:
    - http.host=0.0.0.0
    - transport.host=127.0.0.1
    - xpack.security.enabled=false
    - xpack.monitoring.enabled=false
    - xpack.watcher.enabled=false
    - xpack.graph.enabled=false
    - xpack.ml.enabled=false
    - ES_JAVA_OPTS=-Xms512m -Xmx512m

nginx:
  build: ./nginx
  ports:
    - "80:80"
  volumes:
   - ./nginx/log:/var/log/nginx

kibana:
  image: docker.elastic.co/kibana/kibana:6.2.4
  links:
    - elasticsearch
  ports:
    - "5601:5601"
  environment:
    - SERVER_NAME=localhost
    - ELASTICSEARCH_URL=http://elasticsearch:9200
    - xpack.graph.enabled=false
    - xpack.security.enabled=false
    - xpack.ml.enabled=false
